import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { Header } from "../layout/Header/Header";
import { Footer } from "../layout/Footer/Footer";
import { Sidebar } from "../layout/Sidebar/Sidebar";
import { getMenu } from "../../api/api";
import { MenuItem } from "../../interfaces/menu.interface";
import { AppContextProvider } from "../../context/app.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Top-app",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const firstCategory = 0;
    const menu: MenuItem[] = await getMenu(firstCategory);

    return (
        <html lang="ru">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Noto+Sans:wght@300;400;500;700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className={inter.className}>
                <div className="grid grid-cols-main_mobile grid-rows-main min-h-screen gap-x-[30px] gap-y-10 md:grid-cols-main grid-areas-main_mobile md:grid-areas-main">
                    <AppContextProvider
                        menu={menu}
                        firstCategory={firstCategory}
                    >
                        <Header className="grid-in-header md:hidden" />
                        <Sidebar className="grid-in-sidebar hidden md:grid" />
                    </AppContextProvider>
                    <div className="grid-in-body p-[15px] md:p-0">
                        {children}
                    </div>
                    <Footer className="grid-in-footer" />
                </div>
            </body>
        </html>
    );
}
